/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   printf.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jkalia <jkalia@student.42.us.org>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/03/22 20:17:03 by jkalia            #+#    #+#             */
/*   Updated: 2017/03/29 13:42:31 by jkalia           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include <limits.h>
#include <stdint.h>
#include <wchar.h>

int		main(int ac, char **av)
{

	printf("%C\n", 'a');
//	printf("%-100c\n", 'a');
//	printf("%-c\n", 'a');
	/**
	int		d = 333;
	printf("%020d\n", d);
	printf("%020.3d\n", d);
	printf("%020.5d\n", d);


	//printf("%-10x\n", 333);
	//printf("%f\n", (double)d);
	//printf("%-10d\n", -333);
	printf("%a", (double)333);
	printf("%a", (double)42);
	printf("%a", (double)-0);
	printf("Kashim a %a histoires à raconter", (double)1001);
	printf("Il fait au moins %a\n", (double)-8000);
	printf("%%a 0000042 == |%a|\n", (double)0000042);
	printf("%%a Lydie == |%a|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%a", (double)-0);
	printf("%a", (double)0);
	printf("%a", (double)INT_MAX);
	printf("%a", (double)INT_MIN);
	printf("%a", (double)INT_MIN - 1);
	printf("%a", (double)INT_MAX + 1);
	printf("%%a \t == |%a|\n", (double)'\t');
	printf("%%a 42.42 == |%a|\n", 42.42);
	printf("%A", (double)42);
	printf("Kashim a %A histoires à raconter", (double)1001);
	printf("Il fait au moins %A\n", (double)-8000);
	printf("%A", (double)-0);
	printf("%A", (double)0);
	printf("%A", (double)INT_MAX);
	printf("%A", (double)INT_MIN);
	printf("%A", (double)INT_MIN - 1);
	printf("%A", (double)INT_MAX + 1);
	printf("%%A 0000042 == |%A|\n", (double)0000042);
	printf("%%A \t == |%A|\n", (double)'\t');
	printf("%%A Lydie == |%A|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%A 42.42 == |%A|\n", 42.42);
	printf("%%A 42.42 == |%.2A|\n", 42.42);
	printf("Kashim a %c histoires à raconter", 1001);
	printf("Il fait au moins %c\n", -8000);
	printf("%c", 42);
	printf("%c", -0);
	printf("%c", 0);
	printf("%c\n", INT_MAX);
	printf("%c\n", '\n');
	printf("%c\n", 'c');
	printf("%c", 'l');
	printf("%c", 'n');
	printf("%c", 'y');
	printf("%c", ' ');
	printf("%c", 'e');
	printf("%c", 's');
	printf("%c", 't');
	printf("%c", ' ');
	printf("%c", 'f');
	printf("%c", 'a');
	printf("%c", 't');
	printf("%c", 'a');
	printf("%c", 's');
	printf("%c", 't');
	printf("%c", 'i');
	printf("%c", 'q');
	printf("%c", 'u');
	printf("%c", 'e');
	printf("%c\n", '!');
	printf("%c\n", '\r');
	printf("%c\n", '\t');
	printf("%d", 42);
	printf("Kashim a %d histoires à raconter", 1001);
	printf("Il fait au moins %d\n", -8000);
	printf("%d", -0);
	printf("%d", 0);
	printf("%d", INT_MAX + 1);
	printf("%d", INT_MIN);
	printf("%d", INT_MIN - 1);
	printf("\n");
	printf("%d", INT_MAX + 1);
	printf("%%d 0000042 == |%d|\n", 0000042);
	printf("%%d \t == |%d|\n", '\t');
	printf("%%d Lydie == |%d|\n", 'L'+'y'+'d'+'i'+'e');
	printf("%lla\n", (long long) 32);
	printf("%e", (double)42);
	printf("Kashim a %e histoires à raconter", (double)1001);
	printf("Il fait au moins %e\n", (double)-8000);
	printf("%e", (double)-0);
	printf("%e", (double)0);
	printf("%e", (double)INT_MAX);
	printf("%e", (double)INT_MIN);
	printf("%e", (double)INT_MIN - 1);
	printf("%e", (double)INT_MAX + 1);
	printf("%%e 0000042 == |%e|\n", (double)0000042);
	printf("%%e \t == |%e|\n", (double)'\t');
	printf("%%e Lydie == |%e|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%e 42.42 == |%e|\n", 42.42);
	printf("%E", (double)42);
	printf("Kashim a %E histoires à raconter", (double)1001);
	printf("Il fait au moins %E\n", (double)-8000);
	printf("%E", (double)-0);
	printf("%E", (double)0);
	printf("%E", (double)INT_MAX);
	printf("%E", (double)INT_MIN);
	printf("%E", (double)INT_MIN - 1);
	printf("%E", (double)INT_MAX + 1);
	printf("%%E 0000042 == |%E|\n", (double)0000042);
	printf("%%E \t == |%E|\n", (double)'\t');
	printf("%%E Lydie == |%E|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%E 42.42 == |%E|\n", 42.42);
	printf("%%E 42.42 == |%.2E|\n", 42.42);
	printf("%f", (double)42);
	printf("Kashim a %f histoires à raconter", (double)1001);
	printf("Il fait au moins %f\n", (double)-8000);
	printf("%f", (double)-0);
	printf("%f", (double)0);
	printf("%f", (double)INT_MAX);
	printf("%f", (double)INT_MIN);
	printf("%f", (double)INT_MIN - 1);
	printf("%f", (double)INT_MAX + 1);
	printf("%%f 0000042 == |%f|\n", (double)0000042);
	printf("%%f \t == |%f|\n", (double)'\t');
	printf("%%f Lydie == |%f|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%f 42.42 == |%f|\n", 42.42);
	printf("%F", (double)42);
	printf("Kashim a %F histoires à raconter", (double)1001);
	printf("Il fait au moins %F\n", (double)-8000);
	printf("%F", (double)-0);
	printf("%F", (double)0);
	printf("%F", (double)INT_MAX);
	printf("%F", (double)INT_MIN);
	printf("%F", (double)INT_MIN - 1);
	printf("%F", (double)INT_MAX + 1);
	printf("%%F 0000042 == |%F|\n", (double)0000042);
	printf("%%F \t == |%F|\n", (double)'\t');
	printf("%%F Lydie == |%F|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%F 42.42 == |%F|\n", 42.42);
	printf("%%F 42.42 == |%.2F|\n", 42.42);
	printf("%g", (double)42);
	printf("Kashim a %g histoires à raconter", (double)1001);
	printf("Il fait au moins %g\n", (double)-8000);
	printf("%g", (double)-0);
	printf("%g", (double)0);
	printf("%g", (double)INT_MAX);
	printf("%g", (double)INT_MIN);
	printf("%g", (double)INT_MIN - 1);
	printf("%g", (double)INT_MAX + 1);
	printf("%%g 0000042 == |%g|\n", (double)0000042);
	printf("%%g \t == |%g|\n", (double)'\t');
	printf("%%g Lydie == |%g|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%g 42.42 == |%g|\n", 42.42);
	printf("%G", (double)42);
	printf("Kashim a %G histoires à raconter", (double)1001);
	printf("Il fait au moins %G\n", (double)-8000);
	printf("%G", (double)-0);
	printf("%G", (double)0);
	printf("%G", (double)INT_MAX);
	printf("%G", (double)INT_MIN);
	printf("%G", (double)INT_MIN - 1);
	printf("%G", (double)INT_MAX + 1);
	printf("%%G 0000042 == |%G|\n", (double)0000042);
	printf("%%G \t == |%G|\n", (double)'\t');
	printf("%%G Lydie == |%G|\n", (double)'L'+'y'+'d'+'i'+'e');
	printf("%%G 42.42 == |%G|\n", 42.42);
	printf("%%G 42.42 == |%.2G|\n", 42.42);
	printf("%i", 42);
	printf("Kashim a %i histoires à raconter", 1001);
	printf("Il fait au moins %i\n", -8000);
	printf("%i", -0);
	printf("%i", 0);
	printf("%i", INT_MAX);
	printf("%i", INT_MIN);
	printf("%i", INT_MIN - 1);
	printf("%i", INT_MAX + 1);
	printf("%%i 0000042 == |%i|\n", 0000042);
	printf("%%i \t == |%i|\n", '\t');
	printf("%%i Lydie == |%i|\n", 'L'+'y'+'d'+'i'+'e');
	printf("%Le", (long double)42);
	printf("Kashim a %Le histoires à raconter", (long double)1001);
	printf("Il fait au moins %Le\n", (long double)-8000);
	printf("%Le", (long double)-0);
	printf("%Le", (long double)0);
	printf("%Le", (long double)INT_MAX);
	printf("%Le", (long double)INT_MIN);
	printf("%Le", (long double)INT_MIN - 1);
	printf("%Le", (long double)INT_MAX + 1);
	printf("%Le", (long double)LONG_MAX);
	printf("%Le", (long double)LONG_MIN);
	printf("%Le", (long double)LONG_MIN - 1);
	printf("%Le", (long double)LONG_MAX + 1);
	printf("%%Le 0000042 == |%Le|\n", (long double)0000042);
	printf("%%Le \t == |%Le|\n", (long double)'\t');
	printf("%%Le Lydie == |%Le|\n", (long double)'L'+'y'+'d'+'i'+'e');
	printf("%%Le 42.42 == |%Le|\n", (long double)42.42);
	printf("%C\n", L'ø');
	printf("%D", 42);
	printf("Kashim a %D histoires à raconter", 1001);
	printf("Il fait au moins %D\n", -8000);
	printf("%D", -0);
	printf("%D", 0);
	printf("%D", INT_MAX);
	printf("%D", INT_MIN);
	printf("%D", INT_MIN - 1);
	printf("%D", INT_MAX + 1);
	printf("%%D 0000042 == |%D|\n", 0000042);
	printf("%%D \t == |%D|\n", '\t');
	printf("%%D Lydie == |%D|\n", 'L'+'y'+'d'+'i'+'e');
	printf("%%-d 42 == %-d\n", INT_MIN);
	printf("%%-i -42 == %-i\n", -42);
	printf("%%-4d 42 == |%-4d|\n", 42);
	printf("%%-5d -42 == |%-5d|\n", -42);
	printf("|%3i|%-3i|\n", 42, 42);
	printf("%%-4i 42 == |%-4i|\n", 42);
	printf("%o", 42);
	printf("Kashim a %o histoires à raconter", 1001);
	printf("Il fait au moins %o\n", -8000);
	printf("%o", -0);
	printf("%o", 0);
	printf("%o", INT_MAX);
	printf("%o", INT_MIN);
	printf("%o", INT_MIN - 1);
	printf("%o", INT_MAX + 1);
	printf("%%o 0000042 == |%o|\n", 0000042);
	printf("%%o \t == |%o|\n", '\t');
	printf("%%o Lydie == |%o|\n", 'L'+'y'+'d'+'i'+'e');
	printf("%%+i 42 == %+i\n", 42);
	printf("%%+d 42 == %+d\n", INT_MAX);
	printf("%%+i -42 == %+i\n", -42);
	printf("%%+04d 42 == %0+04d\n", 42);
	printf("%%-5.3s LYDI == |%-5.3s|\n", "LYDI");
	printf("%% 4.5i 42 == |% 4.5i|\n", 42);
	printf("%%04.5i 42 == |%04.5i|\n", 42);
	printf("%%04.3i 42 == |%04.3i|\n", 42);
	printf("%%04.2i 42 == |%04.2i|\n", 42);
	printf("%s", "pouet");
	printf(" pouet %s !!\n", "camembert");
	printf("%s !\n", "Ceci n'est pas un \0 exercice !");
	printf("%s!\n", "Ceci n'est toujours pas un exercice !");
	printf("%s", "Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Lesenfantsnesententpastrestresbonmaiscac'estparcequ'ilsfontcacadansleurculotteetquecen'estvraimentpastrestrespropreNonmongroscoupdecœurc'étaitunsoirde2005,j'étaisinvitéàuneconférenceàLaSorbonnepourparlerdelachansonfrancaiseetdel'écrituredetexteavecpleinsd'autresgens.ParmilesstarsémergentesilyavaitOliviaRuizquietaitentraindedevenirunestaravecsachansonsurlechocolatàlacon.Brefjeelretrouvecoincélorsd'une\"atelierderéflexion\"entreOliviaetRichardCrossquicommençaitàêtrepasmalconnudanslemilieuencemomentàcausedequelquesémissionsdeteréalité.J'aibienrigoleavecOliviaRuizcesoirlà,jeluiparlaitdemonrêved'écritetunechansondepirate,elledelafaçonqu'elleavaitd'écriredeschansons\"commeellessortaient\"etdes'étonnerparfoisqued'autrestrouventcabien.Brefçac'étaitunechouettesoirée/nuitquis'estterminéeauxalentoursde7hdumatinenprenantuncaféauChaidel'AbbayeprèsdeMabillon.Avantqu'ellenedisparaissepourtoujoursdemonexistence.JesuissouventrepasséauChaitôtlematinenespérantlarevoirmaisniet.Rien.JusteChristineScottThomasaperçuunjeudimatinoùilfaisaitchaud.Etalafinilla*bip*");
	printf("%%#X 42 ==  %#X\n", 42);
	printf("%%X 42 ==  %X\n", 42);
	printf("%%#o 0 ==  %#o\n", 0);
	printf("%%o 0 ==  %o\n", 0);
	printf("%%#o INT_MAX ==  %#o\n", INT_MAX);
	printf("%%o INT_MAX ==  %o\n", INT_MAX);
	printf("%%#o INT_MIN ==  %#o\n", INT_MIN);
	printf("%%o INT_MIN ==  %o\n", INT_MIN);
	printf("%%#X INT_MIN ==  %#X\n", INT_MIN);
	printf("%%X INT_MIN ==  %X\n", INT_MIN);
	printf("%%#X INT_MAX ==  %#X\n", INT_MAX);
	printf("%%X INT_MAX ==  %X\n", INT_MAX);
	printf("%%      i 42 == |%      i|\n", 42);
	printf("%% i -42 == |% i|\n", -42);
	printf("%% 4i 42 == |% 4i|\n", 42);
	printf("%%-*.3s LYDI == |%-*.3s|\n", 5, "LYDI");
	printf("%% *.5i 42 == |% *.5i|\n", 4, 42);
	printf("%%*i 42 == |%*i|\n", 5, 42);
	printf("%%*i 42 == |%*i|\n", 3, 42);
	printf("%%*i 42 == |%*i|\n", 2, 42);
	printf("%u", 42);
	printf("Kashim a %u histoires à raconter", 1001);
	printf("Il fait au moins %u\n", -8000);
	printf("%u", -0);
	printf("%u", 0);
	printf("%u", INT_MAX);
	printf("%u", INT_MIN);
	printf("%u", INT_MIN - 1);
	printf("%u", INT_MAX + 1);
	printf("%%u 0000042 == |%u|\n", 0000042);
	printf("%%u \t == |%u|\n", '\t');
	printf("%%u Lydie == |%u|\n", 'L'+'y'+'d'+'i'+'e');
	printf("%x", 42);
	printf("Kashim a %x histoires à raconter", 1001);
	printf("Il fait au moins %x\n", -8000);
	printf("%x", -0);
	printf("%x", 0);
	printf("%x", INT_MAX);
	printf("%x", INT_MIN);
	printf("%x", INT_MIN - 1);
	printf("%x", INT_MAX + 1);
	printf("%%x 0000042 == |%x|\n", 0000042);
	printf("%%x \t == |%x|\n", '\t');
	printf("%%x Lydie == |%x|\n", 'L'+'y'+'d'+'i'+'e');
	printf("%%04i 42 == |%04i|\n", 42);
	printf("%%05i 42 == |%05i|\n", 42);
	printf("%%0i 42 == |%0i|\n", 42);
	printf("%%0d 0000042 == |%0d|\n", 0000042);
	return (0);
	**/
}
